// <auto-generated />
namespace DomainDrivenDesign.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedFluentApiconfigurationsAndOverrodedefaultEntityFrameWorkDefaults : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFluentApiconfigurationsAndOverrodedefaultEntityFrameWorkDefaults));
        
        string IMigrationMetadata.Id
        {
            get { return "201804262031042_Added FluentApi configurations And Overrode default EntityFrameWork Defaults "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
